### ISSUE TITLE
--label CLI option is not supported

### ISSUE THREAD

**Issue by richardjennings** [thegeeklab/drone-docker-buildx#131]
I cannot see an option to pass Labels to be applied via buildx build --label

Is there are specific reason for this omission ?

**Comment by xoxys** [comment]
Well because nobody has implemented it so far.

**Comment by richardjennings** [comment]
> Well because nobody has implemented it so far.

I attempted a PR https://github.com/thegeeklab/drone-docker-buildx/pull/132
