### ISSUE TITLE
Cannot use custom  mirror,ex mirror: registry.docker-cn.com

### ISSUE THREAD

**Issue by blank-1** [thegeeklab/drone-docker-buildx#133]
.drone.yml
- name: package
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    registry: harbor.xxx.org
    mirror: registry.docker-cn.com
    purge: true
    compress: true
    insecure: true
    platforms: linux/arm64,linux/amd64
    username:
      from_secret: IMAGE_USERNAME
    password:
      from_secret: IMAGE_PASSWORD
    dockerfile: ./deploy/Dockerfile
    repo: xxx/xxxx/xx
    tags: apline

error-log
latest: Pulling from thegeeklab/drone-docker-buildx
+ /usr/local/bin/dockerd --data-root /var/lib/docker --host=unix:///var/run/docker.sock --insecure-registry harbor.kylincloud.org --registry-mirror registry.docker-cn.com
Detected registry credentials
+ /usr/local/bin/docker version
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 22:59:14 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
time="2022-09-21T06:30:07Z" level=fatal msg="execution failed: exit status 1"

**Comment by xoxys** [comment]
Does it work without the mirror?

> Cannot connect to the Docker daemon at unix:///var/run/docker.sock

This error seems to be completely unrelated to the usage of a mirror.

**Comment by xoxys** [comment]
Closing due to missing feedback.
