### ISSUE TITLE
Insecure registry

### ISSUE THREAD

**Issue by error0x001** [thegeeklab/drone-docker-buildx#153]
Hello there!

I have a problem with insecure registry. In the pligin/docker it resolves via `insecure=true`, but buildx requires `http=true`. So I have an error in the push step
`#51 ERROR: failed to do request: Head "https://nexus.homelab:30081/v2/rutor/blobs/sha256:2a233a409eb616a7a51e76192fdcffc9ffbd00297fa8bb623aec4430a3c8a490": http: server gave HTTP response to HTTPS client`

Could you add this point to the config file, please?

Proof is here - https://github.com/docker/buildx/issues/163#issuecomment-544714677

**Comment by xoxys** [comment]
Hello, there is already a `config` option that can be used to set a custom buildkit config.

**Comment by error0x001** [comment]
@xoxys thank you so much! I have fixed it. But one more question. As I know it requires toml, not json config. So I use it as

```
      buildkit_config: |
        [registry."nexus.homelab:30081"]
          http = true
          insecure = true
```

because JSON is not working.

```
+ /usr/local/bin/docker buildx create --use --config /tmp/buildkit.json
ERROR: failed to parse config: (1, 1): parsing error: keys cannot contain { character
time="2022-11-24T11:09:28Z" level=fatal msg="execution failed: exit status 1"
```

Config example is here - https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md. I think to use toml config is more valid than json. What do you think?

**Comment by xoxys** [comment]
Sorry for the delay. Glad to hear you got it working. I need to check why we have used json initially, can't remember to be honest. But yes, it looks like toml is the way to go :+1:
