### ISSUE TITLE
Support for a new SBOM setting

### ISSUE THREAD

**Issue by pjbgf** [thegeeklab/drone-docker-buildx#215]
Trying to gauge interest from maintainers on a new setting `sbom` to enable the use of the [upstream SBOM](https://docs.docker.com/build/attestations/sbom/) feature.

Would it be OK to create a PR to that effect?

**Comment by xoxys** [comment]
Sure, I am happy to check a PR. There is already https://github.com/thegeeklab/drone-docker-buildx/pull/171 that disables Provenance by default. At least for the documentation part, we might need to mention that for this feature users need to enable this option as well.

**Comment by pjbgf** [comment]
Thank you for the quick reply. On the PR I did not mention around `--provenance`, as at least upstream they are largely orthogonal features. Please let me know in the PR if that needs changing.

**Comment by xoxys** [comment]
Thanks again!
