### ISSUE TITLE
why the default DNS is 8.8.8.8 and how to use local dhcpd dns 

### ISSUE THREAD

**Issue by bonjour-py** [thegeeklab/drone-docker-buildx#223]
as the title

**Comment by bonjour-py** [comment]
![图片](https://user-images.githubusercontent.com/33248848/227193249-6cca9d94-0676-4086-aea4-9cf2409c00af.png)

**Comment by xoxys** [comment]
Because that's the default from `dockerd`, see https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-dns-options. 

There is a [plugin parameter](https://drone-plugin-index.geekdocs.de/plugins/drone-docker-buildx/#parameters) to set a custom DNS.

**Comment by bonjour-py** [comment]
i don't think this is a good idea to set a customized parameter a defaut. it should be a 'not set'. 
besides that is NOT a default from dockerd. the defalut is 'not set'. plz?

**Comment by bonjour-py** [comment]
😅 i don't know what my DNS is , i'm running it in a 'docker in docker' in a pod of  k8s . i don't think i should to manually set a dns

**Comment by xoxys** [comment]
This plugin does not set any DNS server and as I said already, using 8.8.8.8 is the internal default of dockerd. Please read https://docs.docker.com/config/containers/container-networking/#dns-services.

> The IP address of a DNS server. To specify multiple DNS servers, use multiple --dns flags. If the container can’t reach any of the IP addresses you specify, it uses Google’s public DNS server at 8.8.8.8. This allows containers to resolve internet domains.

**Comment by bonjour-py** [comment]
sry my bad

**Comment by xoxys** [comment]
Were you able to test the latest release? Does it work for you as expected?
