### ISSUE TITLE
Allow passing --config to the buildx container

### ISSUE THREAD

**Issue by aspriddell** [thegeeklab/drone-docker-buildx#31]
Would it be possible to add the `--config` parameter to the `docker buildx create --use` command that's run? Use case is to be able to push to an insecure/self signed registry.

I've started to implement this on [my fork](https://github.com/aspriddell/drone-docker-buildx/tree/add-config-switch), but have almost no golang knowledge and had little success testing the changes (but will still look into it).

**Comment by xoxys** [comment]
Thanks for your report. In general, yes, why not as long as it does not end up in a maintenance hell. Your commits doesn't look that bad, so I would be happy to review a PR and discuss remaining implementation details.
