### ISSUE TITLE
Make envsubst

### ISSUE THREAD

**Issue by tomaswarynyca** [thegeeklab/drone-docker-buildx#36]
Would it be possible to add variables or commands in the options. 
When the command is executed, it will be replaced by the corresponding line? 
How is it possible that inside the repo you put the repository that is in a secret?

**Comment by xoxys** [comment]
Thanks for your report. Environment vars substitution within the config file is not supported right now. Its recommended to use existing plugin parameters in favor of passing a raw config file whenever possible. Drone secrets/env variables can be passed to plugin parameters by default.

**Comment by tomaswarynyca** [comment]
In my case I use a private registry
```
registry: { from_secret: registry }
repo: registry.domain.com/name/repository
```
How should I put the secret registry, instead of registry.domain.com ?

**Comment by xoxys** [comment]
If I understand your question correctly, that's not possible and not how Drone plugins work in general. If you want to use a Drone secret for a parameter, you have to use the full value. In your case, you need two Drone secrets, one for `registry` and one for `repo` (personally I don't thing that a URL is a secret that need to be protected as a secret, but that might depend):

```
registry: { from_secret: registry }
repo: { from_secret: repo }
```

I'm not away of any other way and that's nothing I would like to fix in a single plugin, sorry. If you like, you could ask in the drone support channel if there is another solution available as this behavior is the same for all drone plugins.

**Comment by tomaswarynyca** [comment]
But if I use `repo: registry.domain.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}` I can't use it in a secret

**Comment by xoxys** [comment]
Thats correct. But thats still a general drone issue.
