### ISSUE TITLE
offer automatic installation of binfmt binaries

### ISSUE THREAD

**Issue by aspriddell** [thegeeklab/drone-docker-buildx#39]
In order to use commands like `apt install` in a dockerfile, the emulator binaries need to be installed on the host. One way of doing so is by running `docker run --privileged --rm tonistiigi/binfmt --install all`.

Is it viable to add this as an option to run at each build, to save people using such plugins time creating another step using docker-in-docker to run this command?

For some further context, this command is needed when using things like GitHub actions and the image in the example above is the same one the official [docker setup for GitHub actions](https://github.com/docker/setup-qemu-action/blob/4259ef6ecbcec7c4d4cbb9dddf7220865a2b13fd/src/main.ts#L18) uses.

**Comment by xoxys** [comment]
Not sure if I would like to have such a 3rd party depenency in the plugin... Why is it useful for drone environments? If you use static agents/single server you just need to install it once together with the drone setup. If you use dynamic agents/autoscaler drone provides other ways e.g. userdata to pre-setup your agents. Why would you need to execute it on every single pipeline run?

**Comment by aspriddell** [comment]
Not sure myself, but I've had to run it twice on the same server over the course of 3 weeks - it sometimes randomly stops working. I see it as this plugin allows buildx to work, but in order for buildx to work the emulators need to be installed, hence why I would like to see this supported out-the-box. If you disagree that's fine, but personally for such a simple addition (single config switch and a single command) I don't see much of an issue

**Comment by xoxys** [comment]
Well my main concern is the security aspect as it grants a 3rd party full root access to the drone agents which could lead to a supply chain attack. I use this plugin on two drone servers with an autoscaler setup and never saw the emulators stop working.

As it is really easy to just add this 3rd party image to your drone pipelines if it necessary I will not add to the plugin itself for now, sorry.

**Comment by aspriddell** [comment]
fwiw, this error occurs when emulating arm64 on x64. Either way, I'll probably go build my own plugin that can handle this as it's not a complex task
