### ISSUE TITLE
Does this plugin support `docker buildx bake`?

### ISSUE THREAD

**Issue by eastwd** [thegeeklab/drone-docker-buildx#42]
I have a question. Does this plugin support `docker buildx bake`?

 docker-bake.hcl is flexible and reusable format. It's possible to maintain the drone.yaml more simple.
https://github.com/docker/buildx/blob/master/docs/reference/buildx_bake.md

**Comment by xoxys** [comment]
Thanks for your report. We don't support `buildx bake` and right now I think we will not implement it. Degrade drone plugins do a simple wrapper while you have to maintain more and more single config files for each drone plugin feels wrong to me while it increases the complexity of the plugin. I couldn't find a feature that `bake` provides that is not already possible right now.

**Comment by eastwd** [comment]
I understand. Thank you for explaining!
