### ISSUE TITLE
Squash

### ISSUE THREAD

**Issue by modem7** [thegeeklab/drone-docker-buildx#51]
Heya, is squash supported by this plugin at this time?

I tried it but getting some unsupported errors, so just making sure it's not an ID10T issue.

Thanks!

**Comment by xoxys** [comment]
Hi, to be honest I have never used it on my own bit it should work. We just pass the `--squash` cli flag if the plugin parameter is set to true see https://github.com/thegeeklab/drone-docker-buildx/blob/main/plugin/docker.go#L91

**Comment by modem7** [comment]
Hmmmm. 

I'm getting "Squash build flag is only available when Docker deamon is started with experimental flag. Ignoring..." if I don't enable experimental, and if I do:

error: squash currently not implemented

**Comment by xoxys** [comment]
Hmm but that sounds like a docker daemon issue. The plugin use the official docker dind image and basically just starts the docker daemon and construct the cli command based on the plugin options. Not sure if we can solve on the plugin side.

**Comment by modem7** [comment]
Hmmm, interesting:

https://github.com/docker/buildx/issues/727

**Comment by xoxys** [comment]
Can we consider this as closed for this plugin? I don't see how we could solve it (other than removing the option from the plugin).

**Comment by modem7** [comment]
I think so. 

It may be worthwhile removing it at this point until it can be confirmed as working, just to avoid any unecessary confusion.
