### ISSUE TITLE
auto_tag not skipping builds correctly

### ISSUE THREAD

**Issue by djmaze** [thegeeklab/drone-docker-buildx#65]
When using the `auto_tag` option and pushing a non-master branch, the plugin outputs the following:

```
time="2022-01-08T23:20:44Z" level=info msg="skipping automated docker build for refs/heads/<my-branch>"
```

But still, it continues building the branch.

I can see that the message is logged [in the `Validate()` function](https://github.com/thegeeklab/drone-docker-buildx/blob/276f215b24e5ae1e9459a2aaa7b1dc5a7476b9ab/plugin/impl.go#L95), but the build is not prevented from running there.

**Comment by xoxys** [comment]
Thanks for the issue and the PR. Could you explain the use case? I'm a bit confused, as the skip flag will  avoid executing the entire plugin. If you want to skip the plugin at all, you should handle this with drone conditions in your pipeline config and not per plugin. Otherwise, every plugin would have to implement it on its own.

The log text might be a bit confusing and could be improved, but the intention is to skip just the tagging + pushing to the registry. But the build command will always be executed, as this is the core functionality of the plugin.

**Comment by djmaze** [comment]
I just tried it again. When pushing in my non-master branch, the tagging and pushing is _not_ skipped, but the image is still tagged and pushed as `latest`. (That's with `thegeeklab/drone-docker-buildx:20`, I should add.)

I can try to change my PR so that only the tagging and pushing is skipped?

**Comment by xoxys** [comment]
Ok, that's indeed not expected, and I think I found the issue. Could you change your to PR to extend this line https://github.com/thegeeklab/drone-docker-buildx/blob/main/plugin/docker.go#L87 to `if !dryrun && len(build.Tags.Value()) > 0`? This should avoid pushing the image with an empty tag list, and the tag list is empty by default and should still be empty if auto_tag ist used on a none-default branch.

**Comment by djmaze** [comment]
Sorry for the late reply. Your suggestion does not work as is, because `latest` is also in `build.Tags` for my non-default branch.

**Comment by djmaze** [comment]
I guess that behaviour is also not as expected. I would expect `latest` to only be tagged in the default branch..

**Comment by xoxys** [comment]
Are you sure it is in build.tags? Checking the code I cant see where this should come from. That latest is pushed is IMO caused by `docker push` without a specidied tag but I might be wrong. Can take a closer look tomorrow.

**Comment by xoxys** [comment]
Ah found it... Its set in the default slice... Ok need to think about it a bit more.

**Comment by djmaze** [comment]
Yes, that was taken over from the original plugin. It did work there because the rest of the build [is completely skipped there](https://github.com/drone-plugins/drone-docker/blob/f08821b02496bfa8814d688523e170156050128f/cmd/drone-docker/main.go#L322-L328). By the way, that also means this plugins behaves differently in that respect.

**Comment by xoxys** [comment]
That it behaves different is fine for me. There was a reason why also the original docker plugin and some other were forked :) I still think skipping the entire plugin execution is wrong and can be done in Drone config easily. I tend to set `build.Tags` to an empty list by default and add the `len(build.Tags.Value()) > 0` condition. This should result in:

- the plugin always builds the docker image if it is executed
- use `auto_tag` to tag `latest` on the configured default branch or `latest` + semVer tags on a matching tag
- use `tags` or a `.tags` file to specify the tags that should be used manually

In addition:
- `dryrun` can always be used to skip the publishing conditionally in the Drone config

**Comment by djmaze** [comment]
Sounds good to me.

**Comment by xoxys** [comment]
Would you like to put it in your PR? Otherwise I can take care later today.

**Comment by djmaze** [comment]
Will have time this evening and can have a look.
