### ISSUE TITLE
Build documentation could be more exact

### ISSUE THREAD

**Issue by djmaze** [thegeeklab/drone-docker-buildx#67]
To build the binary correctly and in the correct path for the docker image, I need to do the following:

```bash
 cd cmd/drone-docker-buildx && go build -v -a -tags netgo -o ../../release/amd64/drone-docker-buildx; cd ../..
```

Afterwards, the `docker build ..` command works correctly.

**Comment by xoxys** [comment]
Thanks for reporting!
