### ISSUE TITLE
Allow to set build output to tar file

### ISSUE THREAD

**Issue by lafriks** [thegeeklab/drone-docker-buildx#70]
Would be nice (especially in combination with dryrun option) to set output to tar file where build result would be written to so that it could be checked with [trivy](https://aquasecurity.github.io/trivy) later on.

This could be done using command `--output=type=tar,dest=/path/to/tar/output`

**Comment by djmaze** [comment]
Funny. I had this implemented in my fork, but threw it away because it turned out I don't necessarily need it.

But it was really quick to implement. Could come up with a PR unless someone else wants to do this.

**Comment by xoxys** [comment]
PR is very welcome :)
