### ISSUE TITLE
Multiple Build contexts

### ISSUE THREAD

**Issue by modem7** [thegeeklab/drone-docker-buildx#93]
Heya, 

I've just seen this: https://www.docker.com/blog/dockerfiles-now-support-multiple-build-contexts/ 

Just curious if multiple build contexts will be considered in future, or this this something that "`build_args`" would cover?

**Comment by xoxys** [comment]
Hi, sure, we can add a config option for the build-context flag. `build_args` is a different flag and won't help.

**Comment by xoxys** [comment]
Sorry for the delay. I have tagged a new release with this feature, please give it a try.
